### ISSUE TITLE
add DOI to citation

### ISSUE THREAD

**Issue by walterxie** [denisekuehnert/bdmm#25]
@denisekuehnert 
It will be nice to add DOI in the citations for a better summary, for example, to change `@Citation` in `PiecewiseBirthDeathMigrationDistribution` to:

```Java
@Citation("Kuehnert D, Stadler T, Vaughan TG, Drummond AJ. (2016). " +
		"Phylodynamics with migration: \n" +
		"A computational framework to quantify population structure from genomic data. \n" +
		"Mol Biol Evol. 33(8):2102–2116.",
                DOI= "10.1093/molbev/msw064", year = 2016, firstAuthorSurname = "Kuehnert")
```

I do not have the access, otherwise I can update this for you.
https://doi.org/10.1093/molbev/msw064

**Comment by denisekuehnert** [comment]
Done.
