### ISSUE TITLE
template have no aux-entries

### ISSUE THREAD

**Issue by rbouckaert** [denisekuehnert/bdmm#26]
Got a user asking "just trying to set up an analysis with bdmm and noted that the bmodel test is not available between the options for the site model. is there some workaround/xml hacking  to make it work with bdmm or there is some specific reason why it is not there?"

It turns out adding <mergepoint id='aux-sitemodel-panels’/> at line 175 of the BEAUti template fixed this.
New substitution models, site models, clock models etc that are not part of the standard set attempt to merge themselves with the main template. If you add more mergepoints like in the standard template (see[ Standard.xml](https://github.com/CompEvol/beast2/blob/master/templates/Standard.xml)) it should fix the problem.

**Comment by denisekuehnert** [comment]
Done.
