### ISSUE TITLE
Set up xml : state changes occuring at transmission times 

### ISSUE THREAD

**Issue by GoncheDanesh** [denisekuehnert/bdmm#31]
Hi,
Do we have to modify the xml file to set up the analysis where state changes occur at transmission times (exactly at branching times) instead of at mutations (along a branch) ? If so, how ?
Thank you !

**Comment by denisekuehnert** [comment]
The probability of state changes occurring at transmission times is extremely low in this model, but if you want to have a representation of the posterior trees where this is "enforced" you can use a TypedNodeTreeLogger, see lines 715ff in https://github.com/tgvaughan/MultiTypeTree/blob/master/examples/structuredCoalescent.xml
